### ISSUE TITLE
Permission not working in new plugin

### ISSUE THREAD

**Issue by mananmodi22** [quickapps/cms#138]
Hi,

Have made new plugin, in controller file have made one method testing and defined URL "testing" in route file, now "testing' url is called only when i am logged as super admin (In backend i have given access for  anonymous user to access testing URL) but guest/anonymous user can not access testing url.

It seems permission module not working(URL testing should work for all users as it is already given access from admin panel permission table to all users), please guide us soon is there anything missing here.

Manan

**Comment by mananmodi22** [comment]
ChristopherCastro,

Any comments on above issue?

**Comment by botchris** [comment]
Sounds similar to https://github.com/quickapps/cms/issues/136

Where permissions seems to fail due to cache invalidation. 

It was solved few days ago, so try to update your code in order to integrate the fix. 

Beat Regards! 

---

You can also try to manually clear your permissions cache: remove the directory `/tmp/cache/acl`
