### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by dimple-varshaaweblab** [quickapps/cms#152]
Hello,

  I am trying to change in files under view folder but changes are not reflected as i have checked  CMS and got that it's taking from view cache.cache folder is created first time then whenever we are making any changes it doesn't rewrite files inside cache folder.i am using linux server permission is already given.

Let me explain you in brief. I want to make changes in/vendor/quickapps-plugins/content/src/Template/Admin/Manage/add.ctp as i want to add one more field. but changes are not reflected because i think it's take from view cache and when i remove files from cache changes were reflected. i had checked cache was set for 2 min.but after 2 min also changes not reflected.

**Comment by botchris** [comment]
Hi there,

You should avoid hacking QACMS's core, otherwise you will be unable to
update  QACMS using composer.  If you need to change something you should
the AOP API: http://book.quickappscms.org/developers/aspects.html

However, if you still need to do it you will need to clear TMP/aop cache
after every change.
El 6/6/2016 6:28 a. m., "dimple-varshaaweblab" notifications@github.com
escribió:

Hello,

I am trying to change in files under view folder but changes are not
reflected as i have checked CMS and got that it's taking from view
cache.cache folder is created first time then whenever we are making any
changes it doesn't rewrite files inside cache folder.i am using linux
server permission is already given.

Let me explain you in brief. I want to make changes
in/vendor/quickapps-plugins/content/src/Template/Admin/Manage/add.ctp as i
want to add one more field. but changes are not reflected because i think
it's take from view cache and when i remove files from cache changes were
reflected. i had checked cache was set for 2 min.but after 2 min also
changes not reflected.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/quickapps/cms/issues/152, or mute the thread
https://github.com/notifications/unsubscribe/AAtvl_dpRT_XEMs5rWpzRASwbdJPc8OOks5qI6HfgaJpZM4Iujdb
.

**Comment by dimple-varshaaweblab** [comment]
Hello,

Can you please guide me from where can i change exactly? so changes can be reflected.your help will be highly appreciated.

Thank you
Dimpal Gohil
