### ISSUE TITLE
Field type file dont upload for server

### ISSUE THREAD

**Issue by riconegri** [quickapps/cms#22]
The field type 'File', when added to a new content type (eg Products), is not uploading the files, and probably he who is causing the error "The request has Been black-holed '

**Comment by quickapps** [comment]
I'll take a look,
I think that add the Security component was not a great ideam....  :S

**Comment by riconegri** [comment]
Maybe not the 'Security Component' because the code below disables the same, and the error still continues, which seems to be the 'File Field' error.

public function beforeFilter() {
        parent::beforeFilter();
        if (in_array($this->request->action, array('admin_add', 'admin_edit'))) {
            $this->Security->validatePost = false;
        }
    }

**Comment by quickapps** [comment]
Yes, but you should put that code on the upload handler controller:
.../FieldFile/Controller/UploadifyController.php
(Check your log files you will see that upload handler is being black-holed)

This issue may appear on any Form that contains `CCK fields`...so I think that security component should be removed in order to avoid confusing error messages.
