### ISSUE TITLE
issue ...on Wiki (Core-Hooks), and maybe on title_for_layout_alter

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#38]
Not a real issue, at least not an issue on code.
In the Wiki Core-Hooks page I could see the "content_for_layout_alter()" hook that could be interesting for me ...but there isn't on sources. I presume that sould be changed in "content_alter()" that is ok (and not shown in that page).

Other thing. I tried to use the hook "title_for_layout_alter", it's present on sources but I think doesn't work properly. I tried to change the title (or echos something) and nothing happens on the node rendering

**Comment by quickapps** [comment]
You are right, ´content_for_layout_alter´ is now ´content_alert´.
The ´title_for_layout_alter´ seems to work ok, remember that you must use $this->Layout->title(); in your theme layout. (this hook is invoked by this method).

---

Anyway, I decided to rename those hooks to a more-descriptive-easy-to-remember name.
- ´layout_content_alter´
- ´layout_title_alter´ (this will affect `Seo Tools` module)

Also, a few new hooks added:
- `layout_header_alter`
- `layout_footer_alter`
- `layout_meta_alter`

Check the commit 98a805865af1c55e246bb3735c0d52aa2079f5e9

**Comment by Gabri** [comment]
Perfect!
You're right, layout_title_alter() works very well ...I don't know why but I thought not at the page title ...but at node's titles!  :)

Just a simple question: I'd need to add some content on the bottom of the node rendering, the best with actual hooks it's to do it on the "before_render_node" hook and change the correct $node['Field'][INDEX]['FieldData']['data'], isn't it?
Thanks

**Comment by quickapps** [comment]
Direct manipulation of node fields array is not recommended.

Both `before_render_node` and `after_render_node` methods are supposed to return extra HTML code.
The passed argument ($node) to those methods should be used as information only. e.g.: Return diferent html code based on `node-type`, etc.
(Basically, only hook methods which contain the `_alter` sufix are expected to `alter` the passed argument. The rest of the hooks should return something)

---

So, if you need to add extra content to the bottom of the node you should use `after_render_node`, e.g.:

```
function after_render_node($node) {
    // $node not need here
    return "<div>My extra HTML code</div>";
}
```

BUT,
if you need to add extra content to the bottom of a specific field of the node, then you should manually modify the $node param as you mentioned. e.g.:

```
function before_render_node(&$node) {
    // dont forget the `&`
    $node['alter_the_array'];
    // return not needed
}
```

**BUT, a better way** to do the same above is to use field hooks:
`before_render_field` and `after_render_field`

---

Another solution: themes are able to overwrite default rendering elements...so you can create your own `theme_node.ctp` file as part of your theme and add whatever your need and wherever you need...then QACMS (actually cakephp) will automatically use your custom file instead of the default ones.

**Comment by Gabri** [comment]
Very helpful, thank you very much.
I think it could be interesting to copy and paste what you wrote in the HOW-TO page in the Wiki/Develper section!  :)

**Comment by Gabri** [comment]
I'd add the "before_render_field" and "after_render_field" hooks on the list in Hooks Core Page of the wiki, they are absent
