### ISSUE TITLE
field Image: small issue(s)

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#84]
1) When you upload an image in a field image, it shows the other fields (alt, title) but the icon with che class "file-icon" has a link broken like "http://localhost/ial/field_image/img/icons/image-x-generic.png" 
that says:
MISSING CONTROLLER
Error: FieldImage.ImgController could not be found.
Error: Create the class ImgController below in file: /home/gabri/workspace/ial/QuickApps/Plugin/Field/Fields/FieldImage/Controller/ImgController.php
<?php
class ImgController extends FieldImageAppController {

}
...
But reloading the page the icon now is good (with a different url)
http://localhost/ial/field_file/img/icons/image-x-generic.png

2) when you remove a field from a content type it removes without asking confirmation (I think it could be better have a confirmation for this operation). Other thing (but could be a choice) if that field was a Field File it doesn't empty/remove the folder files

**Comment by quickapps** [comment]
The second point, all of what you said is already implemented (since v1.0 I believe):
-    In content type's fields form, when you press "delete" an alert appears:
   "Delete selected field and all related data, this can not be undone ?"
-    FieldFile & FieldImage, they dont remove any file/folder on Field Instance deletion.
