### ISSUE TITLE
clearing cache clearing theme settings

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#93]
Hello,

Not sure it's an issue.
New fresh installation. Installed QuickShell Module. Created a new Theme with QuickShell. Setted as default. Changed colors on theme configuration. Cleared cache via QuickShell utility, this reset the settings changed in the theme configuration.
It seemed to me a strange behavior...

**Comment by quickapps** [comment]
Because when using the [Configurable Styles](https://github.com/QuickAppsCMS/QuickApps-CMS-Docs/blob/1.x/eng/designers/themes.md#configurable-style) and CommentTags feature, QuickApps actually creates a copy of your original theme's css file, and it's stored as a temp file (cache).

CSS files may be too big to be stored in database, that is why QuickApps creates a cache-file instead of that.
And QuickShell "clear cache" command performs a full cache cleaning, which includes those tmp-css files.

---

I think we could add some extra options to QuickShell's clear-cache command, and choose what things should be removed.

**Comment by Gabri** [comment]
Is not possibile to "simply" persist on db the few variables used on theme configuration? (and regenerate the cache css file after clearing the cache)

**Comment by quickapps** [comment]
Move data to DB and then back to cache sounds a bit unnecessary.
We could simply delete all cache files, except those css-files.

Anyway this is a QuickShell improvement, I'm closing this ticket, but please open a new one in the QuickShell repo so I wont forget about this.

Regards!
